### ISSUE TITLE
Relation to DBTropes?

### ISSUE THREAD

**Issue by deklanw** [raiben/tropescraper#9]
Wondering what this does better than DBTropes? I've been messing with DBTropes and it seems to be missing data. And, Skipforward seems to have more than the DBTrope ntriple dump on their site. So it seems like DBTrope dump < Skipfoward < TVTropes itself?

Does this project improve upon however DBTropes is scraping?

**Comment by brucethemoose** [comment]
I just started investigating this, but maybe DBTropes' scraping isn't being maintained, even though its still running? I too noticed that its missing quite a few tropes on almost every page I sampled online.

I haven't tested this project yet, but it definitely seems more up-to-date and comprehensive in its scraping, albeit more limited in scope.

**Comment by brucethemoose** [comment]
The paper for this code mentions that DBTropes was "unattended" in 2016: https://arxiv.org/pdf/2006.05380

**Comment by deklanw** [comment]
Yes, on the other hand on the webpage it says

```
 A snapshot of all data can be found ​here (NTriples format). It gets updated on a monthly basis. 
```

And when I unzip the dump on the page the file modified date says `7/10/2020`... weird

**Comment by brucethemoose** [comment]
DBTropes might be scraping TVTropes and making zips automatically, but that doesn't necessarily mean its being actively developed and maintained. For example, I found a page for a brand new movie, but it seemingly cut off all the tropes below an ad banner. Also, the homepage hasn't been updated in 4 years.

It'd be nice if the source was posted somewhere...

**Comment by deklanw** [comment]
Agreed.

**Comment by JJ** [comment]
Sorry to arrive so late. Essentially, it's the same, except that TVTropes has changed a lot since then and new scraping code had to be developed; as you mention, DBTropes code wasn't available to start with so we had to start from scratch. We'd appreciate your feedback on this one and how it works for you.
